_LHDspawn = _this select 0;
LHDpos = _LHDspawn;
_LHDdir = getdir _LHDspawn;
_LHDspawnpoint = getposasl _LHDspawn;

_land_lhd_house1 = "Land_LHD_house_1" createVehiclelocal _LHDspawnpoint;
_land_lhd_house2 = "Land_LHD_house_2" createVehiclelocal _LHDspawnpoint;
_land_lhd_elev = "Land_LHD_elev_R" createVehiclelocal _LHDspawnpoint;
_land_lhd1 = "Land_LHD_1" createVehiclelocal _LHDspawnpoint;
_land_lhd2 = "Land_LHD_2" createVehiclelocal _LHDspawnpoint;
_land_lhd3 = "Land_LHD_3" createVehiclelocal _LHDspawnpoint;
_land_lhd4 = "Land_LHD_4" createVehiclelocal _LHDspawnpoint;
_land_lhd5 = "Land_LHD_5" createVehiclelocal _LHDspawnpoint;
_land_lhd6 = "Land_LHD_6" createVehiclelocal _LHDspawnpoint;
_land_lhd_house1 setdir _LHDdir;
_land_lhd_house2 setdir _LHDdir;
_land_lhd_elev setdir _LHDdir;
_land_lhd1 setdir _LHDdir;
_land_lhd2 setdir _LHDdir;
_land_lhd3 setdir _LHDdir;
_land_lhd4 setdir _LHDdir;
_land_lhd5 setdir _LHDdir;
_land_lhd6 setdir _LHDdir;
_land_lhd_house1 setpos _LHDspawnpoint;
_land_lhd_house2 setpos _LHDspawnpoint;
_land_lhd_elev setpos _LHDspawnpoint;
_land_lhd1 setpos _LHDspawnpoint;
_land_lhd2 setpos _LHDspawnpoint;
_land_lhd3 setpos _LHDspawnpoint;
_land_lhd4 setpos _LHDspawnpoint;
_land_lhd5 setpos _LHDspawnpoint;
_land_lhd6 setpos _LHDspawnpoint;

_land_lhd_house1 attachTo [_LHDspawn,[-3.3,-6.15,17],"hatch1"];
_land_lhd_house2 attachTo [_LHDspawn,[-6.49,-46.8,19.07],"hatch1"];
_land_lhd_elev attachTo [_LHDspawn,[2.4,-115.9,0.23],"hatch1"];
_land_lhd1 attachTo [_LHDspawn,[-0.61,84.1,-0.65],"hatch1"];
_land_lhd2 attachTo [_LHDspawn,[-1.23,22.8,-0.65],"hatch1"];
_land_lhd3 attachTo [_LHDspawn,[0,0,0],"hatch1"];
_land_lhd4 attachTo [_LHDspawn,[-2.065,-44.9,1],"hatch1"];
_land_lhd5 attachTo [_LHDspawn,[-2.45,-89.8,0.35],"hatch1"];
_land_lhd6 attachTo [_LHDspawn,[-2.05,-130.8,0.35],"hatch1"];

_pos0 = getposASL _land_lhd_elev select 0;
_pos1 = getposASL _land_lhd_elev select 1;
_pos2 = getposASL _land_lhd_elev select 2;
_pos2o = _pos2;
_scale = 0.01;
_land_lhd_elev enablesimulation false;
